title: Hamid Blog
description: Flexton is a responsive and ultra-minimal theme for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "flexton.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Hamidreza Moradi
author-image:   1.jpg
author-job:     Blockchain Researcher 
author-email:   hamid@europe.com # Add your email for contant form.
author-twitter: newbateni2 # Add your twitter account
about-author:  I am a bachelor's student and my major is CS. I study and research about Blockchain world especially about Ethereum, DeFi, and Bitcoin L2.

# Social settings
social-twitter:   newbateni2
social-facebook:
social-github:    irnb
social-pinterest: 
social-instagram: newbateni
social-youtube:
social-vk:   
social-linkedin: hamidreza-moradi-2b07581a7

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: hamid # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
